# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 141f8233a5d9f4edc78e621f51a789b982cdb742d753f66e887370b3e3380adae475eb660b58928ff489d0f8f633d4b1356bead7fbbfe613647b402ee3e8491e

test:
  secret_key_base: cace285a5f7f5954e65bffd48bb0e31f0c7d35f808706faa8fa8b35e48e516e1060794e926bbe70f99086e8f10f403c02cfa3493350d35aa85397446dd933996

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
